spring:

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


  datasource:
    url: jdbc:mysql://localhost:3306/heyahhhhhwebsite?serverTimezone=Asia/Shanghai
    username: ahhhhh
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

hometown:
  province: Beijing
  city: Beijing
  desc: I'm living in ${hometown.province} ${hometown.city}